### ISSUE TITLE
Rename check-terraform-cf-consistency 

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/cf-ops-automation#11]
Now that the pipeline jobs are common among different providers (cf, openstack, ...) the naming including "cf" in micro-depls pipeline is confusing.

What about removing the "cf" prefix to become `check-terraform-consistency` , `tf-manual-approval`, and `enforce-terraform-consistency` ?

**Comment by o-orand** [comment]
I close this one, it already done:

![image](https://user-images.githubusercontent.com/976115/51388794-bfaeef80-1b2a-11e9-9a65-3e6f4eb1b19d.png)

@gberche-orange , feel free to reopen it.
