### ISSUE TITLE
provide automated non-attended COA env bootstrap

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/cf-ops-automation#113]
User Story outline:
* As a COA contributor, in order to run end-to-end automated tests, I need to set up minimum COA prereq environment
* As a paas-template author, in order to contribute templates, I need to set up COA prereq minimum environment
* As a paas-template operator, in order to deploy paas-template, I need to bootstrap COA prereqs

Acceptance scenario:
- Given raw Iaas prereqs (openstack credentials)
- When I launch the COA bootstrap
- Then transient infrastructure (bosh director / concourse / credhub) is set up
- And [paas-templates](https://github.com/orange-cloudfoundry/paas-templates) micro-deps deployment subset gets deployed with
   - micro-depls/micro-bosh
   - micro-credhub
   - micro-dns
   - micro-minio
   - concourse-micro
   - gitlab + config

**Comment by gberche-orange** [comment]
Alternatives for possible implementation:
- BBL with openstack support https://github.com/cloudfoundry/bosh-bootloader/issues/77#issuecomment-371345635
- BUCC https://github.com/starkandwayne/bucc
- https://github.com/alphagov/paas-bootstrap#readme (leveraging vagrant, tested on AWS )

**Comment by o-orand** [comment]
another alternative: https://github.com/pivotalservices/turbo

**Comment by o-orand** [comment]
To help investigation, using our current bootstrap server, BUCC and BBL have been set up.
* BBL config is available at ~/bbl, it's using 192.168.90.0/24 network
* BUCC config is available at ~/bucc, it's using 192.168.80.0/24 network

**Comment by gberche-orange** [comment]
Status: on a dedicated COA Iaas tenant, a bootstrap vm instanciated a BUCC vm, which launched a concourse which is running COA ci, with the BUCC bosh director to be used to deploy the reference data set (#108)
