### ISSUE TITLE
Add support for multiple errands (automatic and manual ones)

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/cf-ops-automation#14]
Today errand jobs (if there are some for a deployment) are grouped all together in a unique Concourse box.
The request is to have one box by errand job in order to trigger each one separately.
Moreover, we would like to categorize errands job : 
*A manual category means "errand triggered by human (click)" 
*An automatic category means "errand triggered by concourse"

**Comment by o-orand** [comment]
Todo: design errand lifecycle (see PCF as inspiration)
