### ISSUE TITLE
Find and apply global solution to print password in yaml files

### ISSUE THREAD

**Issue by lucaspinto** [orange-cloudfoundry/cf-ops-automation#145]
The password we're using for the different services and pipelines are generated and might contain special characters such as `"` or `'`.

We need to find the best solution to prevent YAML errors while printing them and apply it to wherever we print passwords.

**Comment by o-orand** [comment]
I'm not sure we need to handle `"` or `'`, but we should for other special character: `%, -, > $`. We can escape password like FLY_PASSWORD:  '((concourse-password))' and update  [git-resource](https://github.com/concourse/git-resource#source-configuration) usage to an exacped `username` and `password`
