### ISSUE TITLE
Triggering individual recreate fails with "fatal: reference is not a tree"

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/cf-ops-automation#147]
### Expected behavior

The utils `recreate` job is supposed to trigger recreation of a single bosh deployment

### Observed behavior

The job execution fails with message ``fatal: reference is not a tree: 3e6a3e1ad2c6ae36e6196755a28b0f910cf619ea``

![image](https://user-images.githubusercontent.com/4748380/41231609-d6a2f10a-6d83-11e8-885f-16e89deb351b.png)

The root cause seems that the recreate job take the output of the "recreate-all" resource, whose commit id may not be available anymore in the git resource

![image](https://user-images.githubusercontent.com/4748380/41231394-4470539a-6d83-11e8-9333-3672642befe9.png)

Workaround: trigger the `recreate-all` job instead

### Affected release

Reproduced on version 20.0.0 or commit id 2f10ba8

**Comment by o-orand** [comment]
the main usage is to be able to trigger all recreate jobs through `recreate-all`, and to follow recreation execution for each deployment. So the pipeline is designed to match this expectation. You may trigger a single recreation, when `recreate-all` is in sync. But it is not possible to trigger all recreate jobs in one-click and a single recreation using concourse resource. Single recreate can easily be trigger using bosh-cli. This required some discussion if we want to focus on `single-recreate`

**Comment by gberche-orange** [comment]
workaround: document in FAQ see #124

**Comment by o-orand** [comment]
As we have removed `recreate-all` support from COA, this issue is not relevant anymore see #373
