### ISSUE TITLE
Regression: IAAS_SPEC_PATH is missing in Concourse pipelines 

### ISSUE THREAD

**Issue by aurelienbouleau** [orange-cloudfoundry/cf-ops-automation#151]
### Expected behavior
Service subscription for cloudflare-depls should be still ok after COA v2.0 upgrade

### Observed behavior
Terraform-apply step in concourse fails when customers want to susbscribe to cloudflare-depls.
See error below for more details.

### Affected release

Reproduced on version 2.0

### Traces and logs

Logs from Concourse cloudflare service deployment (terraform-apply)
+ [ -z cloudflare-depls/terraform-config/spec ]
	
+ [ -z  ]
	
+ echo FATAL: IAAS_SPEC_PATH is missing
	
FATAL: IAAS_SPEC_PATH is missing

**Comment by gberche-orange** [comment]
Relates to #56
