### ISSUE TITLE
UX: Include update-pipeline-ops-depls-generated job in tf group 

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/cf-ops-automation#18]
Currently when pushing secret or template changes related to CF or terraform, the pipeline user needs to browse through the `ops-depls-generated` pipeline to check proper execution of `update-pipeline-ops-depls-generated` job and then browse to the TF pipelines/groups (such as  `ops-depls-generated?groups=Terraform`)

It would be great to have the  `update-pipeline-ops-depls-generated` job be part of the `ops-depls-generated?groups=Terraform`

**Comment by o-orand** [comment]
I think we are going to remove ```update-pipeline-ops-depls-generated``` from each generated pipeline. The removal is going to be part of #19.

**Comment by o-orand** [comment]
We won't be able to remove `update-pipeline-xxx-depls-generated`

**Comment by o-orand** [comment]
With new bosh-pipeline, we don't have this issue anymore, update-pipeline is in another pipeline so it is not possible to inclide it.

![image](https://user-images.githubusercontent.com/976115/51390505-c5f39a80-1b2f-11e9-8de7-7705a6ba4a12.png)
