### ISSUE TITLE
Credentials update on pipelines are ignored by depls pipeline

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/cf-ops-automation#183]
### Expected behavior

As an Operator, When updating a credential used by concourse pipeline, I want Concourse to automatically detect and use these credentials.

### Observed behavior

When bosh credentials are updated, `<root-deployment>-depls-generated` ignore it, and `<root-deployment>-depls-init-generated` need to be manually triggered.

**Workaround**: manually trigger the job in `<root-deployment>-depls-init-generated`

### Affected release

Reproduced on version v2.2

### Traces and logs

We don't scan files described in `ci-deployment-overview.yml`, so Concourse ignores it.

**Comment by poblin-orange** [comment]
same issue on coa 3
changing the bosh director password is not propagated to the ops-depls pipelines.
triggering ops-depls-init-generated didnt help.

**Comment by o-orand** [comment]
Check if it still occur on new bosh pipelines

**Comment by o-orand** [comment]
Closing: cannot reproduce on v 4.1
