### ISSUE TITLE
support cpi-config files

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/cf-ops-automation#191]
**Is your feature request related to a problem? Please describe.**
Need to be able to adresse multiple iaas backend from a COA deployment. This requires leveraging the muti-cpi feature of bosh

**Describe the solution you'd like**
ability to compose cpi-config with new COA naming conventions.
https://bosh.io/docs/cpi-config/

**Describe alternatives you've considered**

**Additional context**

cc @o-orand

**Comment by o-orand** [comment]
We share the same naming convention as cloud and runtime config ie:
  - var files:  *-cpi-vars.yml
  - ops files: *-cpi-operators.yml
  - config file: cpi-config.yml
