### ISSUE TITLE
git submodule of a deployment model are not pulled in the on-demand-pipeline context  

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/cf-ops-automation#195]
**Context :** 

We are in a COAB BOSH context (model deployment and instance deployment).

In this context, a BOSH model deployment uses a git sub module (cf-mysql-deployment). The BOSH model deployment define BOSH operators (*-operators) which are symbolic links to operators defined in the sub module. 
[Model deployment]operator -> [Sub module]operator
Through COA, the BOSH model deployment is working properly.

The instance deployment defines BOSH operators (*-operators) which are symbolic links to the model deployment operators which are symlinks  to operators defined in the sub module.  
[Instance deployment]operator -> [Model deployment]operator -> [Sub module]operator
Through COA, the BOSH instances deployments are failing.

**Root cause :** 
The git submodule of the model deployment is not pulled during the manifest time generation of the instance deployment. So the symbolic links are not solved.

**Suggested solution :** 
Add a new property in the deployment-dependencies.yml file in order to tell to COA that it is necessary to pull additional information (extended-scan-path sample) in order to resolve symbolic links. Similar to #63 

This needs to be resistant to the fact that COAB deployment models would need to use this syntax (i.e. express a dependency to themselves)

**Workaround**
coab models to not use a submodule (e.g. for bosh operator files) and instead copy the files directly in paas-templates

**Comment by o-orand** [comment]
Maybe we can split this in two steps:
 1. supports extended scan path for paas-templates, (this one should be quite easy, as quite similar to secrets extended scan path)
 2. supports submodule in extended scan path (this is probably a little bit tricky...)
