### ISSUE TITLE
Allow users to provide a GitHub access token for the "github-release" concourse resource type.

### ISSUE THREAD

**Issue by lucaspinto** [orange-cloudfoundry/cf-ops-automation#219]
### Expected behavior

As a User,
I want to be able to pass my *GitHub Access Token* to the pipelines where the "github-release" resource type is used,
So that I can check the resource without being blocked by GitHub's API limit.

### Observed behavior

At the moment, when pipelines have resources from the "github-release" resource type, they tend to quickly reach GItHub's API request limit, which then cut access to this resource for a given amount of time.

This is reproducible in any pipeline using this resource type. When using the reference dataset, this behaviour can be observed in the resources of the following jobs:
- hello-world-root-depls-bosh-generated/deploy-bosh-deployment-sample
- hello-world-root-depls-generated/deploy-bosh-deployment-sample

This list might not be exhaustive.

This is avoidable by passing it a GitHub's access token.

### Affected release

Reproducible on version 3.2.2, and probably on sooner version.

### Traces and logs

This exact error mesage reads:
```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
[31merror running command: GET https://api.github.com/repos/cloudfoundry-community/vault-boshrelease/releases: 403 API rate limit exceeded for 178.19.222.174. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.); rate reset in 14m20.145910975s
[0m
```

**Comment by lucaspinto** [comment]
I prefer to replace "user" with a persona in the ticket description, and will do so once discussed with @o-orand.

**Comment by lucaspinto** [comment]
Note that we're already using this value elsewhere in the code and that it should be available to the pipelines under the name `cf-ops-automation-git-hub-token`. This means that adding the `access-token` option to the resource type may be enough.

This means adding: `access_token: ((cf-ops-automation-git-hub-token))` to a `source` definition like this one:

https://github.com/orange-cloudfoundry/cf-ops-automation/blob/84ee7d8ca7b84328ba80f1332efa4650a95151b2/concourse/pipelines/template/depls-pipeline.yml.erb#L255-L258

**Comment by o-orand** [comment]
About the naming in pipelines, we should use something like `access-token: ((github-access-token))` 
Indeed ((cf-ops-automation-git-hub-token)) is used in COA ci pipeline
