### ISSUE TITLE
python not present in stemcell Xenial

### ISSUE THREAD

**Issue by OMI69-orange** [orange-cloudfoundry/cf-ops-automation#238]
Cassandra Bosh release can't be fully deployed because 'cqlsh' script can't be executed du to the fact that 'python' was not natively installed on Ubuntu Xenial.
Remark : the same Cassandra'Bosh release work fine with Stemcell Ubuntu Trusty

**Comment by o-orand** [comment]
@omi69-orange cf-ops-automation does not enforce the stemcell by itself,it  is done by paas-templates. But I m not sure it is a good practice to rely on package that not always included. It could be better to include python as bosh package.
