### ISSUE TITLE
cf app support lacks ability to define CF CLI environment variables to tune cf push behavior

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/cf-ops-automation#240]
**Is your feature request related to a problem? Please describe.**

Relates to https://github.com/orange-cloudfoundry/paas-templates/issues/263 which require ability to set  `CF_STAGING_TIMEOUT` environment prior to invoking `cf push` in 

https://github.com/orange-cloudfoundry/cf-ops-automation/blob/4e1174f76152977f2ad67de9b3a68afe65714cd1/scripts/cf/push.sh#L52-L64

**Describe the solution you'd like**

Consider sourcing pre-cf-push.sh so that environment variables defined there gets propagated to cf push invocation

**Describe alternatives you've considered**

- add support for an extra script to define environment variables available at push

**Additional context**

**Comment by o-orand** [comment]
I'd recommend to use `manifest` to set environment variable: https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#env-block rather than a custom support in COA. Like below:
```
---
  ...
  env:
    CF_STAGING_TIMEOUT: 15
```

**Comment by gberche-orange** [comment]
@o-orand please double check https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#env-block, this defines env within the container, but does not control the cf cli behavior during push, see https://github.com/orange-cloudfoundry/paas-templates/issues/263

> cf push deploys the app to a container on the server. The variables belong to the container environment.

**Comment by o-orand** [comment]
@gberche-orange my bad
