### ISSUE TITLE
Record bosh deployment manifest including ops files interpolation

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/cf-ops-automation#242]
**Is your feature request related to a problem? Please describe.**

Currently bosh manifests are recorded the secrets repo following the spruce interpolation, but not including the ops file interpolation. Template authors need to look at rendered manifest in the concourse ui to see ops files being interpolated, and can't search for ops files interpolation under the secrets repo

manifest preprocessing 
https://github.com/orange-cloudfoundry/cf-ops-automation/blob/ec81d77b707fd0c2d6d98cbcd9c29f500d98c12c/concourse/pipelines/template/bosh-pipeline.yml.erb#L549

generated manifest recording
https://github.com/orange-cloudfoundry/cf-ops-automation/blob/ec81d77b707fd0c2d6d98cbcd9c29f500d98c12c/concourse/pipelines/template/bosh-pipeline.yml.erb#L701-L708

**Describe the solution you'd like**

Record the output of the [bosh manifest](https://bosh.io/docs/cli-v2/#manifest) command which includes ops file interpolation, without disclosing credhub secrets which still display as non interpolated.

**Describe alternatives you've considered**

Record the output of [bosh interpolate](https://bosh.io/docs/cli-v2/#interpolate) which presents the drawback of disclosing credhub interpolated secrets

**Comment by o-orand** [comment]
We're recording the manifest provided by  the [cloudfoundry/bosh-deployment-resource](https://github.com/cloudfoundry/bosh-deployment-resource) (see https://github.com/orange-cloudfoundry/cf-ops-automation/blob/ec81d77b707fd0c2d6d98cbcd9c29f500d98c12c/concourse/pipelines/template/bosh-pipeline.yml.erb#L60-L64)
The resource automatically fetches the deployed manifest, so it is not the "spruced" manifest that is recorded (see
https://github.com/orange-cloudfoundry/cf-ops-automation/blob/ec81d77b707fd0c2d6d98cbcd9c29f500d98c12c/concourse/pipelines/template/bosh-pipeline.yml.erb#L658-L682)

**Comment by gberche-orange** [comment]
thanks @o-orand for the clarification

Sorry for the noise.
