### ISSUE TITLE
should be able to skip spruce templating

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/cf-ops-automation#25]
When we have a given xxx deployment, a single xxx.yml in xxx/template directory is not used for bosh deployment.
The concourse automation expects a xxx-tpl.yml file, to be spruced then deployed. However, new credhubs / var-store syntax is not spruce compatible.

A defaut behavior could be to just deploy xxx.yml if present (without spruce templating)

**Comment by o-orand** [comment]
workaround: use pre-bosh-deploy script to manually copy this file.

pre-bosh-deploy.sh:
```bash
cp $BASE_TEMPLATE_DIR/<my-deployment-manifeslt-name>.yml $GENERATE_DIR/<my-deployment-manifeslt-name>.yml
```
