### ISSUE TITLE
bump cf cli 6.44 in cf app support

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/cf-ops-automation#257]
**Is your feature request related to a problem? Please describe.**
cant use recent cf cli support (6.41 cli as of COA 3.4.1)

**Describe the solution you'd like**
need cli 6.44 for coa cf apps automation, see https://github.com/cloudfoundry/cli/releases/tag/v6.44.1

**Comment by o-orand** [comment]
Base image used is still use [cf cli 6.41](https://github.com/alphagov/paas-docker-cloudfoundry-tools/blob/master/cf-cli/Dockerfile), so we need to make a PR to bump on upstream first.

**Comment by o-orand** [comment]
PR done on upstream for v 6.46.1
