### ISSUE TITLE
Use dedicated concourse resource to handle cf app binary

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/cf-ops-automation#28]
To be able to push an application to CF, we need app binaries. We use ```pre-cf-push.sh``` mechanism to download binaries. It's better to use dedicated resource to handle binary download (ie maven, github-release, etc...)

**Comment by gberche-orange** [comment]
alternatively, we could evaluate the terraform cloudfoundry support for applications
https://github.com/orange-cloudfoundry/terraform-provider-cloudfoundry/#applications

`path: (Required) Path to a folder which contains application code, url to a zip/jar, url to a tgz/tar or a git url following the scheme: https://[user:password@]mygit.com/myrepo.git[#tag-or-branch-or-commit-hash]`
