### ISSUE TITLE
Stemcell download link break

### ISSUE THREAD

**Issue by JSimon-Orange** [orange-cloudfoundry/cf-ops-automation#284]
### Expected behavior
As a platform operator, i want COA to download the latest stemcells from internet

### Observed behavior
The pipleline 
 * `micro-depls-s3-stemcell-upload-generated/upload-lastest-bosh-vsphere-esxi-ubuntu-xenial-go_agent`, `master-depls-s3-stemcell-upload-generated/upload-lastest-bosh-vsphere-esxi-ubuntu-xenial-go_agent` and `ops-depls-s3-stemcell-upload-generated/upload-lastest-bosh-vsphere-esxi-ubuntu-xenial-go_agent` can not download stemcell as they change downloading URL.

### Affected release
v 4.0.2

### Traces and logs
From Concourse, we can see that COA cannot access the stemcell :
```
2019/10/22 21:36:47 Head https://s3-accelerate.amazonaws.com/bosh-core-stemcells/456.40/bosh-stemcell-456.40-vsphere-esxi-ubuntu-xenial-go_agent.tgz: Bad Gateway
```
From a browser, we can not access the url : https://s3-accelerate.amazonaws.com/bosh-core-stemcells/456.40/bosh-stemcell-456.40-vsphere-esxi-ubuntu-xenial-go_agent.tgz

When looking at stemcell doc on Bosh.io, we can see that stemcell are now exposed on a new DNS : 
https://bosh-core-stemcells.s3-accelerate.amazonaws.com/456.40/bosh-stemcell-456.40-vsphere-esxi-ubuntu-xenial-go_agent.tgz

(https://bosh.io/stemcells/bosh-vsphere-esxi-ubuntu-xenial-go_agent)

**Comment by o-orand** [comment]
this seems not related to COA, there is a redirect between `s3.amazonaws.com` and `s3-accelerate.amazonaws.com`, so COA should not notice.

**Comment by JSimon-Orange** [comment]
Then i close this issue
