### ISSUE TITLE
bosh deployment support for vars property with leading /

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/cf-ops-automation#30]
as reusing on the shelf manifest, deploy fails with vars file property defined with a leading /

See https://github.com/cloudfoundry/bosh-cli/pull/300
Guess the concourse resource used by cf-automation should leverage the latest bosh cli v2. Version 
https://github.com/cloudfoundry/bosh-deployment-resource

NB: bosh cli version 2.0.36 is ok with this syntax.

/cc @o-orand  @gberche-orange

**Comment by o-orand** [comment]
This is now fixed by  concourse resource.
