### ISSUE TITLE
bump terraform flexible engine to version 1.11

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/cf-ops-automation#308]
**Is your feature request related to a problem? Please describe.**
Hitting issue trying to create a nat gateway service on Flexible Engine eu-west-0

**Describe the solution you'd like**
bump COA to https://github.com/terraform-providers/terraform-provider-flexibleengine/releases/tag/v1.11.0

**Comment by o-orand** [comment]
closed by #309
