### ISSUE TITLE
bosh deployment template/*.yml change do not seem to trigger git change scan

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/cf-ops-automation#31]
Updating a file xx-tpl.yml in template triggers the git scan and the concourse deployment.
It seems xx.yml file (non spruced file) do not trigger the git scan.
(context:  deply cloudfoundry job, ops-automation v1.3-prod)
If confirmed, this is a blocker for bosh2 manifest files.

**Comment by o-orand** [comment]
Weird, using cloudfoundry deployment as sample, pipeline scans : 
 - secrets changes on ["ops-depls/cloudfoundry","shared"]
 - templates changes on ["ops-depls/cloudfoundry",.gitmodules]

**Comment by o-orand** [comment]
@poblin-orange are you still see this issue after pipeline reworks (maybe related to #19) ?

**Comment by o-orand** [comment]
Closing cannot reproduce with COA >=1.9. Please reopen if you encounter this issue again.
