### ISSUE TITLE
Support Iaas specific TF configs loading

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/cf-ops-automation#38]
This is a refinement of the [iaas-specifics-support](https://github.com/orange-cloudfoundry/cf-ops-automation#iaas-specifics-support) to include terraform resource.

Currently, the current automation picks all TF config files. 

https://github.com/orange-cloudfoundry/cf-ops-automation/blob/7a09101d2f7d62c74ffef4475c954a80a8227298/concourse/tasks/terraform_plan_cloudfoundry.yml#L50-L57

Sharing the same cf-ops-automation based templates across root deployments leveraging distinct TF config (e.g. openstack and cloudstack) is likely to dammage TF config readeability

The apparent TF syntax support is the [conditional support in interpolation](https://www.terraform.io/docs/configuration/interpolation.html):

```
    A common use case for conditionals is to enable/disable a resource by conditionally setting the count:

    resource "aws_instance" "vpn" {
      count = "${var.something ? 1 : 0}"
    }

    In the example above, the "vpn" resource will only be included if "var.something" evaluates to true. Otherwise, the VPN resource will not be created at all.
```

Wrapping this logic into modules only enables to factor out the conditionals variable and does not alleviate the readability issue causes in every invoked resources having the conditional  count interpolation as illustrated into https://github.com/hashicorp/terraform/issues/12906#issuecomment-336533842 

It may make more sense to conditionally load different TF config files depending on a per root deployment flag (such as in `ci-deployment-overview.yml` `ci-deployment.x-depl.terraform_config.iaas_spec-prefix`)

This may for instance translate into naming convention on additional directories where to fetch iaas-specific spec files such as "specs-openstack" and "specs-cloudstack"

**Comment by o-orand** [comment]
Existing Iaas_type works for bosh deployment has been make through #60 and #102.
