### ISSUE TITLE
Contact SNCF

### ISSUE THREAD

**Issue by msansen-esncf** [orange-cloudfoundry/cf-ops-automation#394]
Bonjour,

Désolé pour l'approche mais je n'ai pas trouvé d'autre moyen. Coté hebergement SNCF on regarde de loin le sujet Cloudfoundry et j'aurais aimé savoir si on pourrait avoir un retour d'experience de votre part, sur vos usages, les reussites/echecs, les zones d'usages?

Merci d'avance

Mathieu (dot) SANSEN
@sncf.fr

**Comment by o-orand** [comment]
Bonjour,
Désolé pour cette réponse tardive, nous ne sommes pas en mesure de faire un tel retour.
