### ISSUE TITLE
Add delete lifecycle

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/cf-ops-automation#4]
Currently, the generated pipelines include deploy, and recreate. The delete phase is still a manual operation done interactively with each resource provider (bosh, cf, iaas)

Adding a paused delete pipeline would help automation for delete.

A pre_delete hook would be useful, e.g. to backup/export data before delete.

**Comment by poblin-orange** [comment]
Im not sure the deployment delete should part of the pipelines generation. 
Currently, the git repos describe a target state.
We might just have a garbage collection job, identifying the deployment described (in paas-template) but not deployed (no enable-deployment.yml marker file), and deleting the related deployment if present in bosh.
A manual step for this garbage collection might be usefull for operators, to review the deployment list before deleting the deployment

**Comment by o-orand** [comment]
closing as a first implementation of delete exists.
