### ISSUE TITLE
Include support for bosh ops files 

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/cf-ops-automation#6]
Such support would be quite useful both at the root-deployment and deployment level

http://bosh.io/docs/cli-ops-files.html
Support in the bosh deployment resource: https://github.com/cloudfoundry/bosh-deployment-resource#out-deploy-a-bosh-deployment

**Comment by poblin-orange** [comment]
convention could be:

xx-ops.yml
xx-ops-tpl.yml => standard spruce templating => xx-ops.yml => used as -o file in bosh cli v2 deploy / concourse resource.

xx-vars.yml
xx-vars-tpl.yml => standard spruce templating => xx-vars.yml => used as -vars file in bosh cli v2 deploy / concourse resource.

**Comment by gberche-orange** [comment]
Lack of documentation of path format in the resource, however example of wildcard into https://github.com/cloudfoundry/bosh-deployment-resource/blob/b8c1feafee9129644e5c4eccd42c1d1cddda8a00/ci/pipeline.yml#L162

About ordering of ops file and vars files when specified as a wildcard:


Seems the concourse resources uses the bosh cli code to resolve file path argument
https://github.com/cloudfoundry/bosh-deployment-resource/blob/master/bosh/director.go#L78
https://github.com/cloudfoundry/bosh-cli/blob/master/cmd/ops_file_arg_test.go

Did not yet find related code for wildcard expansion
