### ISSUE TITLE
delete lifecyle does not clean up generated bosh manifest in secrets repo

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/cf-ops-automation#65]
For each bosh deployment, the generated pipeline commit the generated manifest in the paas-secret repo. However, the delete lifecycle does not remove the  generated bosh manifest, resulting into a leak paas-secret

https://github.com/orange-cloudfoundry/cf-ops-automation/blob/ba94fc66d18bdffe239c4e3f62c8d396348df8d6/concourse/pipelines/template/depls-pipeline.yml.erb#L281-L286

**Comment by o-orand** [comment]
This is also closed by 0c46982
