### ISSUE TITLE
delete-lifecyle does not support clean up of paas-template instances

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/cf-ops-automation#67]
delete-lifecyle current implementation compare the paas-template deployment templates and paas-secret deployment config to identify candidate deployments for deletion.

In the context of on-demand deployments that produce both dynamic templates in paas-template and deployment config in paas-secret, then the current implementation prevents COAB from cleaning up the dynamic service instance deployment in paas-template, otherwise no candidate deployments for deletion get identified.

This results into COAB generating files leak into paas template. For example, a smoke test on each COAB deployment would leak 5-10 files in paas-template in each.

**Comment by gberche-orange** [comment]
A possible UX is to add support for state management in the on-demand paas-template support (e.g. a file marking a paas-template on-demand deployment as "requested-for-deletion"). 

I.e. COAB marks a paas-template subdeployment as marked for deletion. COA can then clean up the subdeployment as part of the deletion execution.

**Comment by gberche-orange** [comment]
With an history of 95 deployments, this triggers 95 bosh tasks, which is observed to take 40 mins lately on our integration environment.

We may need to consider collapsing the bosh tasks to speed up execution. Suspecting this many tasks might contribute to #16

![image](https://user-images.githubusercontent.com/4748380/41545558-bba0ecc0-731b-11e8-9f48-329e35ed4250.png)

**Comment by o-orand** [comment]
I'm not sure it possible, because as we use merge all feature branches into a single branch, COA is not able to know the branch to commit the cleanup. Maybe COAB should handle this in a 2 steps delete.

**Comment by gberche-orange** [comment]
Alternative UX and impl drafted during backlog review with @o-orand and @lucaspinto : 

COA deletes bosh deployments that are not in the expected desired state, by querying bosh for existing bosh deployments. An extra list of protected deployments enables an operator to selectively keep/protect some  deployments (e.g. for further analysis of potentially undelete)

* An operator (or COAB) requests a deployment deletion 
   * A deployment not in the expected/desired state through either
      * Disabled deployment (i.e. present in template repo but absent from config repo)
      * Unknown deployment (i.e. not matching any template and/or config entry) 
         * => COAB would remove entry in template + config
      * + not in the “protected” deployment lists
* List candidate deployment for deletion
   * P=protected deployments lists (specified in the config repo per root deployment)
   * D= List desired deployments (i.e. the some for which a concourse pipeline is generated)
   * A= List current deployments in bosh director
   * C=A-P-D (i.e. the candidates for deletion)
* An operator approves & deletes deletion candidates
   * For each Bosh deployment b in C, 
      * bosh delete b
      * delete associated manifest from git (see related #65)

**Comment by gberche-orange** [comment]
May need to refine the design to respect a `retention period` when deletions are approved.
