### ISSUE TITLE
bump spruce 1.14 - better hybrid spruce / bosh 2 interop

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/cf-ops-automation#70]
Latest version of spruce do ignore bosh 2 vars (credhub var files)
This should help on paas-templates manifests (no more ! escaping)
https://github.com/geofffranks/spruce/releases/tag/v1.14.0

/cc @o-orand

**Comment by o-orand** [comment]
Waiting PR to be merged on https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/108

**Comment by o-orand** [comment]
PR merged, closing
