### ISSUE TITLE
1st class support for private bosh releases

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/cf-ops-automation#81]
As a complement to #12

**Comment by o-orand** [comment]
The pipeline provided  to illustrate upload to private s3 (in #12) can also be used to upload private bosh release. 
@lucaspinto, after our discussion, another possibility, is to modify s3-br-pipeline to handle a private bosh-release provider url and to download tar.gz using a concourse resource (https://github.com/aequitas/concourse-http-resource, https://github.com/pivotalservices/concourse-curl-resource or another resource)

**Comment by o-orand** [comment]
we keep this one  open as we only illustrate pipeline creation based on spruce, we also need an example based on bosh operators/variables.

**Comment by o-orand** [comment]
Closed by #224
