### ISSUE TITLE
generate bosh compiled release pipeline

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/cf-ops-automation#88]
We should optimize the deployment of new stemcells. As cf-ops-automation introduces a privtate s3 to hold / cache the bosh release, it could add a generic mechanism to precompile the releases for the expected stemcell type and version, then populate the root-deployment directors.

for example see http://engineering.pivotal.io/post/compiled-releases-for-pipelines/

**Comment by o-orand** [comment]
This is delivered in COA 5.0.3
