### ISSUE TITLE
add features to purge bosh tasks in a root deployment

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/cf-ops-automation#90]
When overloaded, the bosh director (associated with a root deployment) can lock with a huge number of queued tasks.

An operator would need a concourse job to stop all queued and running tasks.
see http://www.starkandwayne.com/blog/delete-all-bosh-tasks/
```
 bosh  tasks --json | jq .Tables[].Rows[].id -Mr | xargs -n 1 bosh cancel-task 
```

**Comment by o-orand** [comment]
this `cancel-task` job should be added to `utils` group
