### ISSUE TITLE
on cf-app deployments [skip ci] is ignored on secrets repo updates and builds are triggered twice

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/cf-ops-automation#95]
This is a follow up of #74 for cf-apps deployments pipeline (where as the fix in #75 was targeted at bosh deployments pipelines and not yet in `cf-apps-pipeline.yml.erb`)

**Comment by o-orand** [comment]
bad comment: closed by https://github.com/orange-cloudfoundry/cf-ops-automation/commit/b8afb48c4d66c8430ee821efdb56f5fbebb1e5d8. Available with release [1.8.4](https://github.com/orange-cloudfoundry/cf-ops-automation/releases/tag/v1.8.4)
